# Usando uma imagem base do Node.js
FROM node:16

# Definindo o diretório de trabalho no contêiner
WORKDIR /app

# Copiando o package.json e o package-lock.json
COPY package*.json ./

# Instalando as dependências
RUN npm install

# Copiando o restante dos arquivos da aplicação
COPY . .

# Expondo a porta 3000
EXPOSE 3000

# Definindo o comando para iniciar a aplicação
CMD ["node", "index.js"]